### ISSUE TITLE
Broaden Dependency Version Ranges for Better Compatibility

### ISSUE THREAD

**Issue by GabrieleGhisleni** [SpazioDati/llm-elasticsearch-cache#5]
I've noticed that the strict version dependencies for `langchain` and `langchain-community` in the `llm-elasticsearch-cache` package could limit its use in projects with different versions of these dependencies. To improve flexibility and compatibility, I suggest relaxing these version constraints to allow a broader range of versions for both `langchain` and `langchain-community`. This change aims to make the package more adaptable and easier to integrate into various projects.

**Comment by giacbrd** [comment]
fixed in https://github.com/SpazioDati/llm-elasticsearch-cache/commit/6d235361b0797e5db04c144d1744962116739cbd and tested , it should be fine now
